I'm sorry, but an uncaught exception occurred.

After loading the script.
PermissionError: [WinError 5] アクセスが拒否されました。: 'C:\\Users\\shitt\\OneDrive\\ドキュメント\\VisualNovel_Programming\\VisualNovel_Programming\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\main.py", line 529, in main
    if renpy.parser.report_parse_errors():
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\parser.py", line 1791, in report_parse_errors
    renpy.display.error.report_parse_errors(full_text, error_fn)
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\display\error.py", line 177, in report_parse_errors
    error_dump()
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\display\error.py", line 86, in error_dump
    renpy.dump.dump(True)
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\dump.py", line 260, in dump
    os.unlink(filename)
PermissionError: [WinError 5] アクセスが拒否されました。: 'C:\\Users\\shitt\\OneDrive\\ドキュメント\\VisualNovel_Programming\\VisualNovel_Programming\\game\\saves\\navigation.json'

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.1.24090601
VisualNovel_Programming 1.0
Sat Jan 25 16:35:23 2025
