I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    init python:
  File "game/script.rpy", line 21, in <module>
    renpy.image("shiori", im.Scale("shiori.png", 250, 800), yalign=1.0)
TypeError: image() got an unexpected keyword argument 'yalign'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    init python:
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\shitt\Downloads\renpy-8.3.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 21, in <module>
    renpy.image("shiori", im.Scale("shiori.png", 250, 800), yalign=1.0)
TypeError: image() got an unexpected keyword argument 'yalign'

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.1.24090601
VisualNovel_Programming 1.0
Tue Jan 28 19:42:13 2025
